### ISSUE TITLE
INSTALLATION CHALLENGE

### ISSUE THREAD

**Issue by schistomodels** [carlferr/HOME-BIO#3]
Hi,

When I tried running the python HOME_Bio.py config_file.txt command, I got an error because of the os.seteuid() command in the script. 
{
Traceback (most recent call last):
    File "HOME_Bio.py", line 92, in <module>
       main(sys.argv[1:])
    File "HOME_Bio.py", line 85, in main
       os.seteuid(1000)
OSError: [Errno 1] Operation not permitted
}
Since I am not the root user of my HPC, I got stuck. Also, the HPC has singularity rather than docker installed. I did installments anyway by finding singularity equivalents for the commands and steps that require docker but there are still challenges. Is it possible to still run your pipeline using singularity? It would be helpful if you could show how.

Thanks.

**Comment by BioH4z** [comment]
We are very sorry to answer you with such delay.
Unfortunately, we are not planning to improve HOME-BIO on singularity.
If you are able to do that, you can try to modify the script. We were not able to change that because Docker required to be root.
If you have any suggestions, we can try, test it and modify it.
Thank you
