### ISSUE TITLE
Error casued by Script.py

### ISSUE THREAD

**Issue by DooYal** [carlferr/HOME-BIO#4]
The report is listed here:
Traceback (most recent call last):
  File "./Script.py", line 4029, in <module>
    main(sys.argv[1:])
  File "./Script.py", line 122, in main
    output_log=open(split_output_path+"log.txt","w")
PermissionError: [Errno 13] Permission denied: '/home/Output/log.txt'

**Comment by BioH4z** [comment]
Dear DooYal, we are sorry to answer after such delay.
It seems that you do not have permissions to write in the folder. Are you able to generate any file?

**Comment by DooYal** [comment]
> Dear DooYal, we are sorry to answer after such delay. It seems that you do not have permissions to write in the folder. Are you able to generate any file?

I am not sure wether any file was generated, as I found my device lack cache space for unzip Kraken_kaiju database, so I just apply kraken2 for microbiome analysis now.
